AWSTemplateFormatVersion: 2010-09-09
Description: STG309 workshop setup with VPC for Cloud9.
Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: STG309WorkshopInstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  RolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: STG309InstancePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'lambda:CreateFunction'
              - 'lambda:TagResource'
              - 'iam:ListRoleTags'
              - 'iam:ListServerCertificates'
              - 'iam:CreateRole'
              - 'lambda:GetFunctionConfiguration'
              - 'iam:AttachRolePolicy'
              - 'iam:ListServiceSpecificCredentials'
              - 'iam:PutRolePolicy'
              - 'iam:ListSigningCertificates'
              - 'iam:ListVirtualMFADevices'
              - 'iam:ListSSHPublicKeys'
              - 'iam:ListAttachedRolePolicies'
              - 'lambda:ListLayerVersions'
              - 'lambda:ListLayers'
              - 'lambda:DeleteFunction'
              - 'lambda:GetAlias'
              - 'iam:ListRolePolicies'
              - 'iam:ListPolicies'
              - 'iam:GetRole'
              - 'lambda:ListFunctions'
              - 'iam:ListSAMLProviders'
              - 'iam:GetPolicy'
              - 'lambda:GetEventSourceMapping'
              - 'apigateway:*'
              - 'lambda:ListAliases'
              - 'iam:ListEntitiesForPolicy'
              - 'iam:AttachUserPolicy'
              - 'iam:DeleteRole'
              - 'lambda:AddLayerVersionPermission'
              - 'lambda:UpdateAlias'
              - 'lambda:UpdateFunctionCode'
              - 'iam:ListGroupsForUser'
              - 'lambda:ListEventSourceMappings'
              - 'lambda:PublishVersion'
              - 'lambda:CreateAlias'
              - 'iam:GetAccountSummary'
              - 'lambda:ListVersionsByFunction'
              - 'lambda:GetLayerVersion'
              - 'iam:ListPoliciesGrantingServiceAccess'
              - 'iam:DeletePolicy'
              - 'lambda:GetAccountSettings'
              - 'iam:ListMFADevices'
              - 'lambda:GetLayerVersionPolicy'
              - 'lambda:UntagResource'
              - 'lambda:PutFunctionConcurrency'
              - 'iam:ListInstanceProfilesForRole'
              - 'iam:PassRole'
              - 'lambda:ListTags'
              - 'iam:DeleteRolePolicy'
              - 'lambda:DeleteLayerVersion'
              - 'iam:ListAttachedUserPolicies'
              - 'iam:ListAttachedGroupPolicies'
              - 'iam:ListAccessKeys'
              - 'lambda:UpdateEventSourceMapping'
              - 'lambda:GetFunction'
              - 'iam:ListGroupPolicies'
              - 'lambda:UpdateFunctionConfiguration'
              - 'iam:ListRoles'
              - 'iam:ListUserPolicies'
              - 'iam:ListInstanceProfiles'
              - 'iam:CreatePolicy'
              - 'lambda:AddPermission'
              - 'iam:ListPolicyVersions'
              - 'iam:ListOpenIDConnectProviders'
              - 'iam:PutUserPolicy'
              - 'iam:ListAccountAliases'
              - 'iam:ListUsers'
              - 'iam:UpdateRole'
              - 'lambda:DeleteFunctionConcurrency'
              - 'iam:ListGroups'
              - 'lambda:GetPolicy'
              - 'iam:GetLoginProfile'
              - 'iam:DeletePolicyVersion'
              - 'iam:ListUserTags'
            Resource: '*'
      Roles:
        - Ref: RootRole
  RootInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: STG309WorkshopInstanceProfile
      Path: /
      Roles:
        - Ref: RootRole
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.192.0.0/16
      Tags:
        - Key: Name
          Value: C9 VPC
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: C9 IGW
  InternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: us-west-2a
      CidrBlock: 10.192.10.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: C9 Public Subnet
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Public Routes
  DefaultPublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1
  C9IDE:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    DependsOn: PublicSubnet1RouteTableAssociation
    Properties:
      Name: STG309-Workshop
      Description: C9 IDE for STG309 Workshop
      Repositories:
         - PathComponent: /stg309-workshop
           RepositoryUrl: https://github.com/brandold/serverless-object-detection.git
      AutomaticStopTimeMinutes: 60
      SubnetId: !Ref PublicSubnet1
      InstanceType: t2.micro

  EFSSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: STG309Access
      GroupName: STG309
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '0'
        CidrIp: !GetAtt VPC.CidrBlock
      - IpProtocol: udp
        FromPort: '0'
        ToPort: '0'
        CidrIp: !GetAtt VPC.CidrBlock
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '0'
        ToPort: '0'
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: '0'
        ToPort: '0'
        CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC

  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties: 
      AvailabilityZoneName: us-west-2a

  EFSMountTarget:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups: 
        - !GetAtt EFSSecGroup.GroupId
      SubnetId: !Ref PublicSubnet1
